#!/usr/bin/env bash

declare -A os=(["GNU/Linux"]="Linux" ["Darwin"]="MacOSX")

miniforge_version=26.1.0-0
miniforge_fn=Miniforge3-$miniforge_version-${os[$(uname -o)]}-$(uname -m).sh
miniforge_url=https://github.com/conda-forge/miniforge/releases/download/$miniforge_version/$miniforge_fn

activate() {
  . conda/etc/profile.d/conda.sh
  conda activate
}

test ! $(which curl) && echo "Could not find curl" && exit 1

if [[ -d conda ]]; then
  activate
else
  mkdir -p conda
  curl --location --show-error --silent --output conda/$miniforge_fn $miniforge_url
  bash conda/$miniforge_fn -bfp conda
  activate
  conda install --yes conda-build
  conda config --file conda/.condarc --set anaconda_upload no
fi

make package
